/* Pluto Archive - orbit.js */
"use strict";
class Orbit {
 constructor(element){this.element=element;this.radius=Number(element.dataset.radius||200);this.baseSpeed=Number(element.dataset.speed||.1)*1.8*2;this.tilt=Number(element.dataset.tilt||0);this.rotation=0;this.currentSpeed=this.baseSpeed;this.targetSpeed=this.baseSpeed;this.hoverCount=0;this.enabled=true;this.selected=false;this.planets=[];this.trailLength=81;this.trailTimer=0;this.trailInterval=.1;this.trails=new Map();element.querySelectorAll(".planet-wrapper").forEach(w=>{const p=new Planet(w,this);this.planets.push(p);this.createTrail(p)});this.initialize()}
 initialize(){this.element.style.width=`${this.radius*2}px`;this.element.style.height=`${this.radius*2}px`;this.element.style.left="50%";this.element.style.top="50%";this.element.style.transform=`translate(-50%,-50%) rotateX(${this.tilt}deg)`}
 createTrail(p){const a=[];for(let i=0;i<this.trailLength;i++){const e=document.createElement("span");e.className="planet-orbit-trail";Object.assign(e.style,{position:"absolute",width:"7px",height:"7px",borderRadius:"50%",pointerEvents:"none",opacity:"0",background:"rgba(79,216,255,.95)",boxShadow:"0 0 12px rgba(79,216,255,.8)",zIndex:"-100",transformStyle:"preserve-3d"});this.element.appendChild(e);a.push({element:e,x:0,y:0,initialized:false})}this.trails.set(p,a)}
 update(dt){if(!this.enabled)return;this.currentSpeed=damp(this.currentSpeed,this.targetSpeed,5,dt/60);this.rotation+=this.currentSpeed*dt;this.updatePlanets(dt);this.trailTimer+=dt;if(this.trailTimer>=this.trailInterval){this.trailTimer=0;this.recordTrailPositions()}this.renderTrails()}
 updatePlanets(dt){for(const p of this.planets){const a=radians(p.baseAngle+this.rotation*p.orbitMultiplier);p.setPosition(Math.cos(a)*this.radius+this.radius,Math.sin(a)*this.radius+this.radius);p.update(dt)}}
 recordTrailPositions(){for(const p of this.planets){const a=this.trails.get(p);if(!a)continue;for(let i=a.length-1;i>0;i--){a[i].x=a[i-1].x;a[i].y=a[i-1].y;a[i].initialized=a[i-1].initialized}a[0].x=p.x;a[0].y=p.y;a[0].initialized=true}}
 renderTrails(){for(const a of this.trails.values())a.forEach((p,i)=>{if(!p.initialized){p.element.style.opacity="0";return}const f=1-i/a.length;p.element.style.left=`${p.x}px`;p.element.style.top=`${p.y}px`;p.element.style.opacity=String((f*f*.7).toFixed(3));p.element.style.transform=`translate(-50%,-50%) translateZ(-1000px) scale(${.3+f*.7})`;p.element.style.zIndex="-100"})}
 setSpeed(s){this.targetSpeed=s}resetSpeed(){this.targetSpeed=this.baseSpeed}requestSlow(){this.hoverCount++;this.targetSpeed=this.baseSpeed*.05}releaseSlow(){this.hoverCount--;if(this.hoverCount<=0){this.hoverCount=0;this.targetSpeed=this.baseSpeed}}setSelected(s){this.selected=s;this.element.classList.toggle("is-selected",s)}addPlanet(w){const p=new Planet(w,this);this.planets.push(p);this.createTrail(p);return p}removePlanet(p){const i=this.planets.indexOf(p);if(i!==-1){(this.trails.get(p)||[]).forEach(x=>x.element.remove());this.trails.delete(p);this.planets.splice(i,1)}}getPlanet(n){return this.planets.find(p=>p.name===n)}enable(){this.enabled=true}disable(){this.enabled=false}}
