/* Pluto Archive - orbit.js */
"use strict";
class Orbit {
 constructor(element){this.element=element;this.radius=Number(element.dataset.radius||200);this.baseSpeed=Number(element.dataset.speed||.1);this.tilt=Number(element.dataset.tilt||0);this.rotation=0;this.currentSpeed=this.baseSpeed;this.targetSpeed=this.baseSpeed;this.hoverCount=0;this.enabled=true;this.selected=false;this.planets=[];this.trailCanvas=document.createElement("canvas");this.trailCanvas.className="planet-orbit-trails";Object.assign(this.trailCanvas.style,{position:"absolute",left:"0",top:"0",width:"100%",height:"100%",pointerEvents:"none",zIndex:"1"});this.element.appendChild(this.trailCanvas);element.querySelectorAll(".planet-wrapper").forEach(w=>this.planets.push(new Planet(w,this)));this.initialize()}
 initialize(){this.element.style.width=`${this.radius*2}px`;this.element.style.height=`${this.radius*2}px`;this.element.style.left="50%";this.element.style.top="50%";this.element.style.transform=`translate(-50%,-50%) rotateX(${this.tilt}deg)`;this.resizeTrailCanvas()}
 resizeTrailCanvas(){const d=Math.min(devicePixelRatio||1,2);this.trailCanvas.width=this.radius*2*d;this.trailCanvas.height=this.radius*2*d;this.trailCanvas.getContext("2d").setTransform(d,0,0,d,0,0)}
 update(dt){if(!this.enabled)return;this.currentSpeed=damp(this.currentSpeed,this.targetSpeed,5,dt/60);this.rotation+=this.currentSpeed*dt;this.updatePlanets(dt);this.renderTrails()}
 updatePlanets(dt){for(const p of this.planets){const a=radians(p.baseAngle+this.rotation*p.orbitMultiplier);p.setPosition(Math.cos(a)*this.radius+this.radius,Math.sin(a)*this.radius+this.radius);p.update(dt)}}
 renderTrails(){const c=this.trailCanvas.getContext("2d"),cx=this.radius,cy=this.radius;c.clearRect(0,0,cx*2,cy*2);c.lineCap="round";c.lineJoin="round";const trails=[{arc:2.9,width:3.2,alpha:.72},{arc:1.65,width:2.2,alpha:.52},{arc:.88,width:1.4,alpha:.4}];for(const p of this.planets){const h=radians(p.baseAngle+this.rotation*p.orbitMultiplier);for(const t of trails){const n=80,g=c.createLinearGradient(cx+Math.cos(h)*this.radius,cy+Math.sin(h)*this.radius,cx+Math.cos(h-t.arc)*this.radius,cy+Math.sin(h-t.arc)*this.radius);g.addColorStop(0,`rgba(79,216,255,${t.alpha})`);g.addColorStop(.45,`rgba(79,216,255,${t.alpha*.5})`);g.addColorStop(1,"rgba(79,216,255,0)");c.beginPath();for(let i=0;i<=n;i++){const a=h-t.arc*i/n,x=cx+Math.cos(a)*this.radius,y=cy+Math.sin(a)*this.radius;i?c.lineTo(x,y):c.moveTo(x,y)}c.strokeStyle=g;c.lineWidth=t.width;c.shadowBlur=9;c.shadowColor="rgba(79,216,255,.55)";c.stroke()}}c.shadowBlur=0}
 setSpeed(s){this.targetSpeed=s} resetSpeed(){this.targetSpeed=this.baseSpeed} requestSlow(){this.hoverCount++;this.targetSpeed=this.baseSpeed*.05} releaseSlow(){this.hoverCount--;if(this.hoverCount<=0){this.hoverCount=0;this.targetSpeed=this.baseSpeed}} setSelected(s){this.selected=s;this.element.classList.toggle("is-selected",s)} addPlanet(w){const p=new Planet(w,this);this.planets.push(p);return p} removePlanet(p){const i=this.planets.indexOf(p);if(i!==-1)this.planets.splice(i,1)} getPlanet(n){return this.planets.find(p=>p.name===n)} enable(){this.enabled=true} disable(){this.enabled=false}}
