/* Pluto Archive - satellite.js */
"use strict";
class Satellite {
 constructor(planetWrapper){this.wrapper=planetWrapper;this.satellite=planetWrapper.querySelector(".link-satellite");if(!this.satellite)return;this.world=planetWrapper.closest(".orbit")||planetWrapper.parentElement;this.angle=Number(planetWrapper.dataset.satelliteAngle||0);this.speed=Number(planetWrapper.dataset.satelliteSpeed||.42)*1.4;this.radius=Number(planetWrapper.dataset.satelliteRadius||78);this.depth=Number(planetWrapper.dataset.satelliteDepth||52);this.trailLength=210;this.trailTimer=0;this.trail=[];this.createWorldTrail();this.updateVisual()}
 createWorldTrail(){for(let i=0;i<this.trailLength;i++){const e=document.createElement("span");e.className="satellite-orbit-trail";Object.assign(e.style,{position:"absolute",width:"2.5px",height:"2.5px",borderRadius:"50%",pointerEvents:"none",background:"rgba(79,216,255,.95)",boxShadow:"0 0 8px rgba(79,216,255,.85)",opacity:"0",zIndex:"2"});this.world.appendChild(e);this.trail.push({element:e,x:0,y:0,z:0,initialized:false})}}
 update(dt){if(!this.satellite)return;this.angle+=this.speed*dt;this.trailTimer+=dt;if(this.trailTimer>=.5){this.trailTimer=0;this.recordWorldPosition()}this.updateVisual();this.renderWorldTrail()}
 getPosition(){const a=radians(this.angle);return{x:Math.sin(a)*this.radius,z:Math.cos(a)*this.depth}}
 getPlanetWorldPosition(){return{x:this.wrapper.offsetLeft,y:this.wrapper.offsetTop}}
 recordWorldPosition(){const s=this.getPosition(),p=this.getPlanetWorldPosition();for(let i=this.trail.length-1;i>0;i--){this.trail[i].x=this.trail[i-1].x;this.trail[i].y=this.trail[i-1].y;this.trail[i].z=this.trail[i-1].z;this.trail[i].initialized=this.trail[i-1].initialized}this.trail[0].x=p.x+s.x;this.trail[0].y=p.y;this.trail[0].z=s.z;this.trail[0].initialized=true}
 renderWorldTrail(){this.trail.forEach((p,i)=>{if(!p.initialized){p.element.style.opacity="0";return}const f=1-i/this.trail.length,d=clamp((p.z+this.depth)/(this.depth*2),0,1);p.element.style.left=`${p.x}px`;p.element.style.top=`${p.y}px`;p.element.style.transform=`translate(-50%,-50%) translate3d(0,0,${p.z}px) scale(${.2+f*.8})`;p.element.style.opacity=String((f*f*(.35+d*.35)).toFixed(3));p.element.style.zIndex=p.z<0?"1":"20"})}
 updateVisual(){const p=this.getPosition(),d=clamp((p.z+this.depth)/(this.depth*2),0,1),s=.62+d*.38;this.satellite.style.transform=`translate3d(${p.x}px,0,${p.z}px) translate(-50%,-50%) scale(${s})`;this.satellite.style.opacity=(.38+d*.62).toFixed(3);this.satellite.style.zIndex="10"}
}
window.Satellite=Satellite;